package com.emberjs.navigation

import com.emberjs.icons.EmberIcons
import com.emberjs.index.EmberIndices

class EmberAdapterGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.ADAPTER, EmberIcons.ADAPTER_16)
class EmberComponentGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.COMPONENT, EmberIcons.COMPONENT_16)
class EmberControllerGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.CONTROLLER, EmberIcons.CONTROLLER_16)
class EmberHelperGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.HELPER)
class EmberModelGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.MODEL, EmberIcons.MODEL_16)
class EmberRouteGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.ROUTE, EmberIcons.ROUTE_16)
class EmberSerializerGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.SERIALIZER)
class EmberServiceGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.SERVICE, EmberIcons.SERVICE_16)
class EmberTransformGotoClassContributor : EmberGotoClassContributorBase(EmberIndices.TRANSFORM)
